use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'AvaDemo_Example' do
  pod 'AvaDemo', :path => '../'

  target 'AvaDemo_Tests' do
    inherit! :search_paths

    
  end
end
